services:
  worker_service:
    build: ./worker_service
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./worker_service/:/app/
    ports:
      - 8001:8000

  client_service:
    build: ./client_service
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./client_service/:/app/
    ports:
      - 8002:8000
    environment:
      - WORKER_SERVICE_HOST_URL=http://worker_service:8000/api/v1/worker/
      - CHECK_FOR_READY_INTERVAL=30
      - SYNC_INTERVAL=10

  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./nginx_config.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - client_service
      - worker_service
